application: ritstarsite
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /members(/.*)?
  script: members.app

- url: /missions(/.*)?
  script: missions.app

- url: /.*
  script: main.app
